### ISSUE TITLE
Add Contribution.md

### ISSUE THREAD

**Issue by silenteyesoncode** [silenteyesoncode/AI-Powered-News-Article-Classifier-with-History#5]
Tell open devs how can they contribute

**Comment by Kanchan253** [comment]
Hi @silenteyesoncode I would like to work on this. Please assign this to me.Thank you.

**Comment by silenteyesoncode** [comment]
for sure @Kanchan253 

_let me assign you 
feel to make a PR_

if you got any query you shoot me on 7silenteyes07@gmail.com

**Comment by Kanchan253** [comment]
Hi @silenteyesoncode I will create a text file and mail it to you ,please check if it right and then I will make a pull request. Thank you

**Comment by silenteyesoncode** [comment]
Better create a PR only 
As main skill here is writing down the markdown code

If any changes are need I'll add there only 

@Kanchan253

**Comment by Kanchan253** [comment]
Ok sure!

**Comment by silenteyesoncode** [comment]
Better create a PR only 
As main skill here is writing down the markdown code

If any changes are need I'll add there only
